version: "3.7"

services:
  wildbutton-production:
    image: ghcr.io/zozs/wildbutton:latest
    environment:
      PORT: 9850
    env_file:
      - .env.production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
